In [1]:
# Update sklearn to prevent version mismatches
# !pip install sklearn --upgrade

In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
# !pip install joblib

In [3]:
import pandas as pd
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

In [4]:
df_full = pd.read_csv("cumulative.csv")
df_full

rowid     kepid kepoi_name   kepler_name koi_disposition  \
0         1  10797460  K00752.01  Kepler-227 b       CONFIRMED   
1         2  10797460  K00752.02  Kepler-227 c       CONFIRMED   
2         3  10811496  K00753.01           NaN  FALSE POSITIVE   
3         4  10848459  K00754.01           NaN  FALSE POSITIVE   
4         5  10854555  K00755.01  Kepler-664 b       CONFIRMED   
...     ...       ...        ...           ...             ...   
9559   9560  10031643  K07984.01           NaN  FALSE POSITIVE   
9560   9561  10090151  K07985.01           NaN  FALSE POSITIVE   
9561   9562  10128825  K07986.01           NaN       CANDIDATE   
9562   9563  10147276  K07987.01           NaN  FALSE POSITIVE   
9563   9564  10156110  K07989.01           NaN  FALSE POSITIVE   

     koi_pdisposition  koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0           CANDIDATE      1.000              0              0              0   
1           CANDIDATE      0.969              0              0              0   
2      FALSE POSITIVE      0.000              0              1              0   
3      FALSE POSITIVE      0.000              0              1              0   
4           CANDIDATE      1.000              0              0              0   
...               ...        ...            ...            ...            ...   
9559   FALSE POSITIVE      0.000              0              0              0   
9560   FALSE POSITIVE      0.000              0              1              1   
9561        CANDIDATE      0.497              0              0              0   
9562   FALSE POSITIVE      0.021              0              0              1   
9563   FALSE POSITIVE      0.000              0              0              1   

      ...  koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  \
0     ...           -81.0      4.467           0.064          -0.096   
1     ...           -81.0      4.467           0.064          -0.096   
2     ...          -176.0      4.544           0.044          -0.176   
3     ...          -174.0      4.564           0.053          -0.168   
4     ...          -211.0      4.438           0.070          -0.210   
...   ...             ...        ...             ...             ...   
9559  ...          -152.0      4.296           0.231          -0.189   
9560  ...          -166.0      4.529           0.035          -0.196   
9561  ...          -220.0      4.444           0.056          -0.224   
9562  ...          -236.0      4.447           0.056          -0.224   
9563  ...          -225.0      4.385           0.054          -0.216   

      koi_srad  koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0        0.927          0.105         -0.061  291.93423  48.141651      15.347  
1        0.927          0.105         -0.061  291.93423  48.141651      15.347  
2        0.868          0.233         -0.078  297.00482  48.134129      15.436  
3        0.791          0.201         -0.067  285.53461  48.285210      15.597  
4        1.046          0.334         -0.133  288.75488  48.226200      15.509  
...        ...            ...            ...        ...        ...         ...  
9559     1.088          0.313         -0.228  298.74921  46.973351      14.478  
9560     0.903          0.237         -0.079  297.18875  47.093819      14.082  
9561     1.031          0.341         -0.114  286.50937  47.163219      14.757  
9562     1.041          0.341         -0.114  294.16489  47.176281      15.385  
9563     1.193          0.410         -0.137  297.00977  47.121021      14.826  

[9564 rows x 50 columns]

In [5]:
df = df_full.drop(columns = ['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_disposition', 'koi_score', 'koi_tce_delivname'])
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df

koi_pdisposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0           CANDIDATE              0              0              0   
1           CANDIDATE              0              0              0   
2      FALSE POSITIVE              0              1              0   
3      FALSE POSITIVE              0              1              0   
4           CANDIDATE              0              0              0   
...               ...            ...            ...            ...   
9559   FALSE POSITIVE              0              0              0   
9560   FALSE POSITIVE              0              1              1   
9561        CANDIDATE              0              0              0   
9562   FALSE POSITIVE              0              0              1   
9563   FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0    9.488036     2.775000e-05    -2.775000e-05   
1                 0   54.418383     2.479000e-04    -2.479000e-04   
2                 0   19.899140     1.494000e-05    -1.494000e-05   
3                 0    1.736952     2.630000e-07    -2.630000e-07   
4                 0    2.525592     3.761000e-06    -3.761000e-06   
...             ...         ...              ...              ...   
9559              1    8.589871     1.846000e-04    -1.846000e-04   
9560              0    0.527699     1.160000e-07    -1.160000e-07   
9561              0    1.739849     1.780000e-05    -1.780000e-05   
9562              0    0.681402     2.434000e-06    -2.434000e-06   
9563              1    4.856035     6.356000e-05    -6.356000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      170.538750          0.002160  ...           -81.0      4.467   
1      162.513840          0.003520  ...           -81.0      4.467   
2      175.850252          0.000581  ...          -176.0      4.544   
3      170.307565          0.000115  ...          -174.0      4.564   
4      171.595550          0.001130  ...          -211.0      4.438   
...           ...               ...  ...             ...        ...   
9559   132.016100          0.015700  ...          -152.0      4.296   
9560   131.705093          0.000170  ...          -166.0      4.529   
9561   133.001270          0.007690  ...          -220.0      4.444   
9562   132.181750          0.002850  ...          -236.0      4.447   
9563   135.993300          0.010800  ...          -225.0      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.064          -0.096     0.927          0.105         -0.061   
2              0.044          -0.176     0.868          0.233         -0.078   
3              0.053          -0.168     0.791          0.201         -0.067   
4              0.070          -0.210     1.046          0.334         -0.133   
...              ...             ...       ...            ...            ...   
9559           0.231          -0.189     1.088          0.313         -0.228   
9560           0.035          -0.196     0.903          0.237         -0.079   
9561           0.056          -0.224     1.031          0.341         -0.114   
9562           0.056          -0.224     1.041          0.341         -0.114   
9563           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     291.93423  48.141651      15.347  
2     297.00482  48.134129      15.436  
3     285.53461  48.285210      15.597  
4     288.75488  48.226200      15.509  
...         ...        ...         ...  
9559  298.74921  46.973351      14.478  
9560  297.18875  47.093819      14.082  
9561  286.50937  47.163219      14.757  
9562  294.16489  47.176281      15.385  
9563  297.00977  47.121021      14.826  

[8744 rows x 41 columns]

# Select your features (columns)

In [6]:
# Set features. This will also be used as your x values.
X = df.drop(['koi_pdisposition'], axis=1)
y = df['koi_pdisposition'].to_numpy()

y = y.reshape(-1, 1)

print(X.shape)
print(y.shape)

(8744, 40)
(8744, 1)


# Create a Train Test Split

Use `koi_disposition` for the y values

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)


In [8]:
np.unique(y_train)

array(['CANDIDATE', 'FALSE POSITIVE'], dtype=object)

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [9]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
print(X_train_scaled)



[[0.         0.         0.         ... 0.56166305 0.14906817 0.57691966]
 [0.         0.         0.         ... 0.49480475 0.13412518 0.58863737]
 [1.         0.         0.         ... 0.56016589 0.06279284 0.72268087]
 ...
 [0.         1.         0.         ... 0.81646092 0.34711078 0.62414558]
 [0.         0.         1.         ... 0.14633136 0.33520238 0.73439858]
 [0.         0.         0.         ... 0.10882503 0.44980112 0.78215712]]


In [10]:
# for label, original_class in zip(encoded_y, y):
#     print('Original Class: ' + str(original_class))
#     print('Encoded Label: ' + str(label))
#     print('-' * 12)

In [11]:
# select logistic regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier



LogisticRegression(max_iter=1000)

# Train the Model



In [12]:
classifier.fit(X_train_scaled, y_train)
classifier.score(X_test_scaled, y_test)

C:\Users\cro11\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.994053064958829

In [13]:
classifier.coef_

array([[ 8.53496099e+00,  7.46645792e+00,  8.12285231e+00,
         6.79695027e+00,  1.61866259e+00,  2.74073088e-01,
        -2.73232942e-01,  4.11191311e-01,  1.79264341e-01,
        -1.78424194e-01,  4.34335071e-02,  5.70132234e-01,
         7.59450388e-03,  6.45978506e-01,  3.37150794e-01,
        -3.36310647e-01,  1.63548580e+00,  7.60742134e-03,
        -6.76727478e-03,  2.60194480e-02,  4.01495664e-02,
        -2.37163162e-02,  1.27812890e-01,  1.67269709e-02,
         2.66454316e-02, -8.98776549e-03,  1.02857023e+00,
        -6.51901950e-01,  1.54394057e-01,  1.16497999e+00,
        -7.56208750e-01, -3.85075282e-01, -2.39621482e-02,
        -1.12654155e+00,  1.19820793e-01,  2.20502690e-01,
        -8.30501422e-02,  2.48270236e-01, -4.59003377e-01,
        -2.27887342e-02]])

In [14]:
classifier.predict(X_test_scaled)

array(['FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE', ...,
       'FALSE POSITIVE', 'CANDIDATE', 'FALSE POSITIVE'], dtype=object)

In [15]:
# Neural network model

In [16]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
y_test_categorical

C:\Users\cro11\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=40))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               4100      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 202       
Total params: 14,402
Trainable params: 14,402
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [20]:
# Fit the model to the training data
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
205/205 - 1s - loss: 0.1333 - accuracy: 0.9806
Epoch 2/100
205/205 - 0s - loss: 0.0326 - accuracy: 0.9944
Epoch 3/100
205/205 - 0s - loss: 0.0269 - accuracy: 0.9944
Epoch 4/100
205/205 - 0s - loss: 0.0318 - accuracy: 0.9944
Epoch 5/100
205/205 - 0s - loss: 0.0269 - accuracy: 0.9944
Epoch 6/100
205/205 - 0s - loss: 0.0281 - accuracy: 0.9944
Epoch 7/100
205/205 - 0s - loss: 0.0266 - accuracy: 0.9944
Epoch 8/100
205/205 - 0s - loss: 0.0253 - accuracy: 0.9944
Epoch 9/100
205/205 - 0s - loss: 0.0261 - accuracy: 0.9941
Epoch 10/100
205/205 - 0s - loss: 0.0257 - accuracy: 0.9944
Epoch 11/100
205/205 - 0s - loss: 0.0271 - accuracy: 0.9942
Epoch 12/100
205/205 - 0s - loss: 0.0269 - accuracy: 0.9944
Epoch 13/100
205/205 - 0s - loss: 0.0250 - accuracy: 0.9944
Epoch 14/100
205/205 - 0s - loss: 0.0258 - accuracy: 0.9944
Epoch 15/100
205/205 - 0s - loss: 0.0255 - accuracy: 0.9944
Epoch 16/100
205/205 - 0s - loss: 0.0253 - accuracy: 0.9944
Epoch 17/100
205/205 - 0s - loss: 0.0247 - accura

In [21]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

69/69 - 0s - loss: 0.0228 - accuracy: 0.9927
Normal Neural Network - Loss: 0.02283214032649994, Accuracy: 0.9926806688308716


# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# here is code for GridSearch, but my scores are so good it's not necessary


# Create the GridSearchCV model
# from sklearn.model_selection import GridSearchCV
# param_grid = {'C': [1, 5, 10],
#               'gamma': [0.0001, 0.001, 0.01]}
# grid = GridSearchCV(classifier, param_grid, verbose=3)

In [ ]:
# Train the model with GridSearch
# grid.fit(X_train_scaled, y_train_categorical)

In [ ]:
# print(grid2.best_params_)
# print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)